version: '2.1'

volumes:
  mongodb_data: {}

networks:
  restnet:
    driver: bridge

services:
  restheart:
    build: ./restheart
    image: dimaskiddo/ubuntu-oraclejre-restheart:xenial-8.0-3.1
    networks:
      - restnet
    ports:
      - 8080:8080
    environment:
      - MONGODB_USER=restheart
      - MONGODB_PASSWORD=restheart
      - MONGODB_DATABASE=restheart
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    depends_on:
      - mongodb
    restart: always
  mongodb:
    image: centos/mongodb-32-centos7:3.2
    networks:
      - restnet
    environment:
      - MONGODB_USER=restheart
      - MONGODB_PASSWORD=restheart
      - MONGODB_ADMIN_PASSWORD=admin
      - MONGODB_DATABASE=restheart
    volumes:
      - mongodb_data:/var/lib/mongodb/data
    restart: always
